Repository pcaversaccio/snekmate, pull requests merged in 2022-12, with the labels that each got.

#29 🛠 Refactor `MerkleProofVerification` Scripts
  package.json
  src/utils/MerkleProofVerification.vy
  test/utils/MerkleProofVerification.t.sol
  test/utils/scripts/generate-bad-proof.js
  test/utils/scripts/generate-leaf.js
  test/utils/scripts/generate-no-such-leaf.js
  test/utils/scripts/generate-proof-no-such-leaf.js
  test/utils/scripts/generate-proof.js
  test/utils/scripts/generate-root-no-such-leaf.js
  test/utils/scripts/generate-root.js
  yarn.lock
Labels: feature 💥, dependencies 🔁

#33 ✒️ Contributing Guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation 📖

#41 `ERC721`: Use local variable in `safe_mint` function to increment state variable (gas optimisation)
  src/tokens/ERC721.vy
Labels: feature 💥
