Repository pcaversaccio/snekmate, pull requests merged in 2023-02, with the labels that each got.

#67 📖 Add Official Snekmate Style Guide
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
  GUIDELINES.md
  README.md
  src/tokens/ERC20.vy
Labels: documentation 📖, optimisation ⚡️

#68 💥 Implement Fuzz Tests for `CreateAddress` and `Create2Address`
  lib/utils/VyperDeployer.sol
  src/utils/CreateAddress.vy
  test/tokens/ERC20.t.sol
  test/utils/Create2Address.t.sol
  test/utils/CreateAddress.t.sol
  test/utils/ECDSA.t.sol
  test/utils/mocks/MockCallee.sol
Labels: feature 💥, refactor/cleanup ♻️

#79 🥢 Make In-Contract Interface Names Consistent
  src/utils/Create2Address.vy
  src/utils/CreateAddress.vy
  src/utils/EIP712DomainSeparator.vy
Labels: refactor/cleanup ♻️
