Repository pcaversaccio/snekmate, pull requests merged in 2023-01, with the labels that each got.

#52 Base64 Encode: Masking not required to extract first part of block
  .gas-snapshot
  src/utils/Base64.vy
Labels: feature 💥

#54 ✨ ERC-1155 Unit Tests and Mocks
  test/tokens/ERC1155.t.sol
  test/tokens/interfaces/IERC1155Extended.sol
  test/tokens/mocks/ERC1155InvalidReceiverMock.sol
  test/tokens/mocks/ERC1155NonReceiverMock.sol
  test/tokens/mocks/ERC1155ReceiverMock.sol
Labels: feature 💥

#58 ♻️ Add strict ERC1271 Signature Checking in `SignatureChecker.vy`
  README.md
  src/utils/SignatureChecker.vy
  test/utils/SignatureChecker.t.sol
  test/utils/interfaces/ISignatureChecker.sol
Labels: feature 💥

#59 🦹🏼‍♂Change `memory` to `calldata` in Solidity Test Interfaces
  test/tokens/interfaces/IERC1155Extended.sol
  test/utils/interfaces/IBase64.sol
  test/utils/interfaces/IBatchDistributor.sol
  test/utils/interfaces/IECDSA.sol
  test/utils/interfaces/IMerkleProofVerification.sol
  test/utils/interfaces/IMulticall.sol
  test/utils/interfaces/ISignatureChecker.sol
Labels: optimisation 💸

#60 🕓 Add `CHANGELOG`
  CHANGELOG.md
Labels: documentation 📖

#65 🧠 Return `False` Instead of Reverting in `SignatureChecker`
  src/utils/SignatureChecker.vy
  test/utils/SignatureChecker.t.sol
Labels: bug 🐛, optimisation 💸
