Repository pcaversaccio/snekmate, pull requests merged in 2024-03, with the labels that each got.

#212 📖 Fix Comment in `wad_exp`
  src/snekmate/utils/Math.vy
Labels: documentation 📖

#213 ♻️ Restrict Visibility Modifiers in Tests
  .gas-snapshot
  test/auth/AccessControl.t.sol
  test/auth/Ownable.t.sol
  test/auth/Ownable2Step.t.sol
  test/extensions/ERC2981.t.sol
  test/extensions/ERC4626.t.sol
  test/governance/TimelockController.t.sol
  test/tokens/ERC1155.t.sol
  test/tokens/ERC20.t.sol
  test/tokens/ERC721.t.sol
  test/utils/BatchDistributor.t.sol
  test/utils/ECDSA.t.sol
  test/utils/EIP712DomainSeparator.t.sol
  test/utils/Math.t.sol
  test/utils/MerkleProofVerification.t.sol
  test/utils/Multicall.t.sol
  test/utils/SignatureChecker.t.sol
Labels: refactor/cleanup ♻️

#215 🔁 Upgrade Solidity Version to `0.8.25`
  .gas-snapshot
  foundry.toml
  lib/utils/VyperDeployer.sol
  test/auth/AccessControl.t.sol
  test/auth/Ownable.t.sol
  test/auth/Ownable2Step.t.sol
  test/auth/interfaces/IAccessControlExtended.sol
  test/auth/interfaces/IOwnable.sol
  test/auth/interfaces/IOwnable2Step.sol
  test/extensions/ERC2981.t.sol
  test/extensions/ERC4626.t.sol
  test/extensions/interfaces/IERC2981Extended.sol
  test/extensions/interfaces/IERC4626Extended.sol
  test/extensions/mocks/ERC20ExcessDecimalsMock.sol
  test/governance/TimelockController.t.sol
  test/governance/interfaces/ITimelockController.sol
  test/governance/mocks/CallReceiverMock.sol
  test/tokens/ERC1155.t.sol
  test/tokens/ERC20.t.sol
  test/tokens/ERC721.t.sol
  test/tokens/interfaces/IERC1155Extended.sol
  test/tokens/interfaces/IERC20Extended.sol
  test/tokens/interfaces/IERC4494.sol
  test/tokens/interfaces/IERC721Extended.sol
  test/tokens/mocks/ERC1155ReceiverMock.sol
  test/tokens/mocks/ERC721ReceiverMock.sol
  test/utils/Base64.t.sol
  test/utils/BatchDistributor.t.sol
  test/utils/Create2Address.t.sol
  test/utils/CreateAddress.t.sol
  test/utils/ECDSA.t.sol
  test/utils/EIP712DomainSeparator.t.sol
  test/utils/Math.t.sol
  test/utils/MerkleProofVerification.t.sol
  test/utils/Multicall.t.sol
  test/utils/SignatureChecker.t.sol
  test/utils/interfaces/IBase64.sol
  test/utils/interfaces/IBatchDistributor.sol
  test/utils/interfaces/ICreate2Address.sol
  test/utils/interfaces/ICreateAddress.sol
  test/utils/interfaces/IECDSA.sol
  test/utils/interfaces/IEIP712DomainSeparator.sol
  test/utils/interfaces/IMath.sol
  test/utils/interfaces/IMerkleProofVerification.sol
  test/utils/interfaces/IMulticall.sol
  test/utils/interfaces/ISignatureChecker.sol
  test/utils/mocks/Create2Impl.sol
  test/utils/mocks/ERC1271MaliciousMock.sol
  test/utils/mocks/ERC1271WalletMock.sol
  test/utils/mocks/ERC20Mock.sol
  test/utils/mocks/EtherReceiver.sol
  test/utils/mocks/MockCallee.sol
Labels: dependencies 🔁

#216 ♻️ Make `AccessControl` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  GUIDELINES.md
  README.md
  src/snekmate/auth/AccessControl.vy
  src/snekmate/auth/mocks/AccessControlMock.vy
  test/auth/AccessControl.t.sol
  test/auth/interfaces/IAccessControlExtended.sol
Labels: documentation 📖, refactor/cleanup ♻️

#219 ♻️ Make `Ownable2Step` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  GUIDELINES.md
  lib/utils/VyperDeployer.sol
  src/snekmate/auth/Ownable2Step.vy
  src/snekmate/auth/mocks/Ownable2StepMock.vy
  test/auth/Ownable2Step.t.sol
Labels: documentation 📖, refactor/cleanup ♻️
