Repository pcaversaccio/snekmate, pull requests merged in 2024-04, with the labels that each got.

#220 ♻️ Make `TimelockController` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/auth/Ownable2Step.vy
  src/snekmate/auth/mocks/AccessControlMock.vy
  src/snekmate/governance/TimelockController.vy
  src/snekmate/governance/mocks/TimelockControllerMock.vy
  test/governance/TimelockController.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#222 ♻️ Make `Base64` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/utils/Base64.vy
  src/snekmate/utils/mocks/Base64Mock.vy
  test/utils/Base64.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#223 ♻️ Make `BatchDistributor` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/extensions/ERC4626.vy
  src/snekmate/utils/BatchDistributor.vy
  src/snekmate/utils/Multicall.vy
  src/snekmate/utils/mocks/BatchDistributorMock.vy
  test/tokens/mocks/ERC1155ReceiverMock.sol
  test/utils/BatchDistributor.t.sol
  test/utils/mocks/MockCallee.sol
  test/utils/mocks/ReentrancyMocks.sol
Labels: documentation 📖, refactor/cleanup ♻️

#224 ♻️ Make `CreateAddress` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/utils/CreateAddress.vy
  src/snekmate/utils/mocks/CreateAddressMock.vy
  test/utils/CreateAddress.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#225 ♻️ Make `Create2Address` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/utils/Create2Address.vy
  src/snekmate/utils/mocks/Create2AddressMock.vy
  test/utils/Create2Address.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#227 ♻️ Make `ECDSA` Module-Friendly and Carve Out the Message Hash Methods
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/utils/ECDSA.vy
  src/snekmate/utils/MessageHashUtils.vy
  src/snekmate/utils/mocks/ECDSAMock.vy
  src/snekmate/utils/mocks/MessageHashUtilsMocks.vy
  test/utils/ECDSA.t.sol
  test/utils/MessageHashUtils.t.sol
  test/utils/interfaces/IECDSA.sol
  test/utils/interfaces/IMessageHashUtils.sol
Labels: documentation 📖, refactor/cleanup ♻️

#228 ♻️ Make `SignatureChecker` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/utils/SignatureChecker.vy
  src/snekmate/utils/interfaces/IERC1271.vyi
  src/snekmate/utils/mocks/SignatureCheckerMock.vy
  test/utils/SignatureChecker.t.sol
Labels: documentation 📖, feature 💥, refactor/cleanup ♻️

#229 ♻️ Make `EIP712DomainSeparator` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/governance/TimelockController.vy
  src/snekmate/utils/EIP712DomainSeparator.vy
  src/snekmate/utils/mocks/EIP712DomainSeparatorMock.vy
  test/utils/EIP712DomainSeparator.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#232 ♻️ Make `Multicall` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/utils/Multicall.vy
  src/snekmate/utils/mocks/MulticallMock.vy
  test/utils/Multicall.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#233 ♻️ Make `ERC2981` Module-Friendly
  .gas-snapshot
  CHANGELOG.md
  README.md
  src/snekmate/auth/AccessControl.vy
  src/snekmate/extensions/ERC2981.vy
  src/snekmate/extensions/mocks/ERC2981Mock.vy
  test/extensions/ERC2981.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#235 ♻️ Implement Dunder `__interface__` Method and Remove `userdoc` and `devdoc` Sanity Check
  .gas-snapshot
  .github/workflows/checks.yml
  .github/workflows/codeql.yml
  .github/workflows/test-contracts.yml
  scripts/compile.py
  src/snekmate/auth/AccessControl.vy
  src/snekmate/auth/mocks/AccessControlMock.vy
  src/snekmate/auth/mocks/Ownable2StepMock.vy
  src/snekmate/auth/mocks/OwnableMock.vy
  src/snekmate/governance/mocks/TimelockControllerMock.vy
  src/snekmate/tokens/mocks/ERC20Mock.vy
Labels: documentation 📖, ci/cd 👷‍♂️, refactor/cleanup ♻️

#237 ♻️ Make `ERC721` Module-Friendly
  .gas-snapshot
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-test-pypi.yml
  .github/workflows/test-contracts.yml
  CHANGELOG.md
  README.md
  src/snekmate/extensions/mocks/ERC2981Mock.vy
  src/snekmate/governance/TimelockController.vy
  src/snekmate/tokens/ERC1155.vy
  src/snekmate/tokens/ERC721.vy
  src/snekmate/tokens/mocks/ERC721Mock.vy
  src/snekmate/utils/CreateAddress.vy
  src/snekmate/utils/ECDSA.vy
  src/snekmate/utils/EIP712DomainSeparator.vy
  src/snekmate/utils/Math.vy
  src/snekmate/utils/MerkleProofVerification.vy
  src/snekmate/utils/SignatureChecker.vy
  test/governance/TimelockController.t.sol
  test/tokens/ERC721.t.sol
Labels: documentation 📖, refactor/cleanup ♻️

#241 ♻️ Reset `timestamp` in `invariantExecutingNotReadyProposal` Test
  test/governance/TimelockController.t.sol
Labels: refactor/cleanup ♻️
