Repository pcaversaccio/snekmate, pull requests merged in 2024-02, with the labels that each got.

#195 💥 Add Multi-Role-Based `TimelockController` Reference Implementation
  .gas-snapshot
  .gitignore
  .solhint.json
  CHANGELOG.md
  README.md
  package.json
  src/auth/AccessControl.vy
  src/auth/Ownable.vy
  src/auth/Ownable2Step.vy
  src/extensions/ERC2981.vy
  src/governance/TimelockController.vy
  src/tokens/ERC1155.vy
  src/utils/Create2Address.vy
  src/utils/ECDSA.vy
  src/utils/SignatureChecker.vy
  test/extensions/ERC4626.t.sol
  test/governance/TimelockController.t.sol
  test/governance/interfaces/ITimelockController.sol
  test/governance/mocks/CallReceiverMock.sol
  test/tokens/ERC20.t.sol
  test/tokens/ERC721.t.sol
  test/tokens/mocks/ERC721ReceiverMock.sol
  test/utils/EIP712DomainSeparator.t.sol
Labels: documentation 📖, feature 💥, refactor/cleanup ♻️

#201 ♻️ Fix Edge Case in `TimelockControllerInvariants` Tests
  .gas-snapshot
  test/governance/TimelockController.t.sol
Labels: refactor/cleanup ♻️

#203 ♻️ Refactor `TimelockController` Invariant Tests
  .gas-snapshot
  test/governance/TimelockController.t.sol
Labels: refactor/cleanup ♻️

#206 ♻️ Implement `src` Layout
  .gas-snapshot
  .github/workflows/checks.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-test-pypi.yml
  CHANGELOG.md
  README.md
  package.json
  scripts/build.py
  src/snekmate/auth/AccessControl.vy
  src/snekmate/auth/Ownable.vy
  src/snekmate/auth/Ownable2Step.vy
  src/snekmate/auth/interfaces/IAccessControl.vy
  src/snekmate/extensions/ERC2981.vy
  src/snekmate/extensions/ERC4626.vy
  src/snekmate/extensions/interfaces/IERC2981.vy
  src/snekmate/governance/TimelockController.vy
  src/snekmate/tokens/ERC1155.vy
  src/snekmate/tokens/ERC20.vy
  src/snekmate/tokens/ERC721.vy
  src/snekmate/tokens/interfaces/IERC1155.vy
  src/snekmate/tokens/interfaces/IERC1155MetadataURI.vy
  src/snekmate/tokens/interfaces/IERC1155Receiver.vy
  src/snekmate/tokens/interfaces/IERC20Permit.vy
  src/snekmate/tokens/interfaces/IERC4906.vy
  src/snekmate/tokens/interfaces/IERC721Enumerable.vy
  src/snekmate/tokens/interfaces/IERC721Metadata.vy
  src/snekmate/tokens/interfaces/IERC721Permit.vy
  src/snekmate/tokens/interfaces/IERC721Receiver.vy
  src/snekmate/utils/Base64.vy
  src/snekmate/utils/BatchDistributor.vy
  src/snekmate/utils/Create2Address.vy
  src/snekmate/utils/CreateAddress.vy
  src/snekmate/utils/ECDSA.vy
  src/snekmate/utils/EIP712DomainSeparator.vy
  src/snekmate/utils/Math.vy
  src/snekmate/utils/MerkleProofVerification.vy
  src/snekmate/utils/Multicall.vy
  src/snekmate/utils/SignatureChecker.vy
  src/snekmate/utils/interfaces/IERC5267.vy
  test/auth/AccessControl.t.sol
  test/auth/Ownable.t.sol
  test/auth/Ownable2Step.t.sol
  test/extensions/ERC2981.t.sol
  test/extensions/ERC4626.t.sol
  test/governance/TimelockController.t.sol
  test/tokens/ERC1155.t.sol
  test/tokens/ERC20.t.sol
  test/tokens/ERC721.t.sol
  test/utils/Base64.t.sol
  test/utils/BatchDistributor.t.sol
  test/utils/Create2Address.t.sol
  test/utils/CreateAddress.t.sol
  test/utils/ECDSA.t.sol
  test/utils/EIP712DomainSeparator.t.sol
  test/utils/Math.t.sol
  test/utils/MerkleProofVerification.t.sol
  test/utils/Multicall.t.sol
  test/utils/SignatureChecker.t.sol
Labels: ci/cd 👷‍♂️, refactor/cleanup ♻️

#208 📖 Add Note on Memory Usage of Dynamic Arrays in `MerkleProofVerification` Contract
  src/snekmate/utils/MerkleProofVerification.vy
Labels: documentation 📖
